// Cloudflare Pages Function: GET /admin
// Serves the Admin Panel behind HTTP Basic Auth.
// Secrets required: PIX_ADMIN_USER, PIX_ADMIN_PASS

function unauthorized() {
  return new Response('Unauthorized', {
    status: 401,
    headers: {
      'cache-control': 'no-store, max-age=0',
      'www-authenticate': 'Basic realm="PIX Admin", charset="UTF-8"',
    },
  });
}

function checkBasicAuth(request, env) {
  const user = env.PIX_ADMIN_USER;
  const pass = env.PIX_ADMIN_PASS;
  if (!user || !pass) return false;

  const auth = request.headers.get('authorization') || '';
  const m = auth.match(/^Basic\s+(.+)$/i);
  if (!m) return false;

  let decoded = '';
  try {
    decoded = atob(m[1]);
  } catch {
    return false;
  }

  const i = decoded.indexOf(':');
  if (i < 0) return false;

  const gotUser = decoded.slice(0, i);
  const gotPass = decoded.slice(i + 1);
  return gotUser === user && gotPass === pass;
}

function serveHTML() {
  const page = [
    '<!doctype html>',
    '<html lang="pt-br">',
    '<head>',
    '<meta charset="utf-8"/>',
    '<meta name="viewport" content="width=device-width,initial-scale=1"/>',
    '<title>Izzat Eletro - Painel Admin</title>',
    '<link rel="preconnect" href="https://fonts.googleapis.com"/>',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>',
    '<link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" as="style" onload="this.onload=null;this.rel=\'stylesheet\'"/>',
    '<noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"/></noscript>',
    '<script src="https://cdn.tailwindcss.com"><\/script>',
    '<script>tailwind.config={theme:{extend:{fontFamily:{sans:["Inter","system-ui","sans-serif"]}}}}<\/script>',
    '<script src="/assets/js/diagnostics-analyzer.js?v=20260430prof1"><\/script>',
    '<style type="text/css">',
    'body{font-family:Inter,system-ui,sans-serif}',
    '.nav-item{transition:all .15s}',
    '.nav-item:hover{background:rgba(255,255,255,.05)}',
    '.nav-item.active{background:rgba(34,197,94,.12);color:#22c55e}',
    '</style>',
    '</head>',
    '<body class="bg-gray-50 text-slate-800 min-h-screen">',
    '',
    '<!-- Sidebar -->',
    '<div id="sidebar" class="fixed left-0 top-0 bottom-0 w-60 bg-slate-900 text-slate-300 flex flex-col z-10 hidden lg:flex">',
    '  <div class="px-5 py-6 border-b border-white/5">',
    '    <h2 class="text-lg font-extrabold text-white">Izzat Eletro</h2>',
    '    <span class="text-xs text-slate-500">Painel Administrativo</span>',
    '  </div>',
    '  <nav class="p-3 flex-1 flex flex-col gap-1">',
    '    <a class="nav-item active flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-sm font-medium cursor-pointer" onclick="showSection(\'dashboard\')">',
    '      <svg class="w-4 h-4 opacity-70" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>',
    '      Dashboard',
    '    </a>',
    '    <a class="nav-item flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-sm font-medium cursor-pointer" onclick="showSection(\'orders\')">',
    '      <svg class="w-4 h-4 opacity-70" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 01-8 0"/></svg>',
    '      Pedidos',
    '    </a>',
    '    <a class="nav-item flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-sm font-medium cursor-pointer" onclick="showSection(\'pix\')">',
    '      <svg class="w-4 h-4 opacity-70" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>',
    '      Config PIX',
    '    </a>',
    '    <a class="nav-item flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-sm font-medium cursor-pointer" onclick="showSection(\'diagnostics\')">',
    '      <svg class="w-4 h-4 opacity-70" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M4 19V5"/><path d="M4 19h16"/><path d="M8 16V9"/><path d="M12 16V7"/><path d="M16 16v-4"/></svg>',
    '      Diagnostico',
    '    </a>',
    '  </nav>',
    '</div>',
    '',
    '<!-- Mobile header -->',
    '<div class="lg:hidden bg-slate-900 text-white px-4 py-3 flex items-center justify-between sticky top-0 z-10">',
    '  <h2 class="text-base font-extrabold">Izzat Eletro Admin</h2>',
    '  <div class="flex gap-1">',
    '    <button onclick="showSection(\'dashboard\')" class="text-xs px-2.5 py-1.5 rounded bg-white/10 font-medium">Dashboard</button>',
    '    <button onclick="showSection(\'orders\')" class="text-xs px-2.5 py-1.5 rounded bg-white/10 font-medium">Pedidos</button>',
    '    <button onclick="showSection(\'pix\')" class="text-xs px-2.5 py-1.5 rounded bg-white/10 font-medium">PIX</button>',
    '    <button onclick="showSection(\'diagnostics\')" class="text-xs px-2.5 py-1.5 rounded bg-white/10 font-medium">Diag</button>',
    '  </div>',
    '</div>',
    '',
    '<!-- Main content -->',
    '<div class="lg:ml-60 p-4 lg:p-8">',
    '',
    '  <!-- DASHBOARD -->',
    '  <div id="sec-dashboard" class="section">',
    '    <div class="flex justify-between items-center mb-6">',
    '      <h1 class="text-2xl font-extrabold text-slate-900">Dashboard</h1>',
    '      <span class="inline-flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-full bg-green-50 text-green-700"><span class="w-2 h-2 rounded-full bg-green-500"></span>Online</span>',
    '    </div>',
    '    <div class="grid grid-cols-2 lg:grid-cols-3 gap-4 mb-6">',
    '      <div class="bg-white border border-slate-200 rounded-xl p-5">',
    '        <div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Copias PIX</div>',
    '        <div class="text-3xl font-extrabold text-green-600" id="pixClicks">0</div>',
    '      </div>',
    '      <div class="bg-white border border-slate-200 rounded-xl p-5">',
    '        <div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Pedidos Hoje</div>',
    '        <div class="text-3xl font-extrabold text-slate-800" id="ordersToday">0</div>',
    '      </div>',
    '      <div class="bg-white border border-slate-200 rounded-xl p-5">',
    '        <div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Total Pedidos</div>',
    '        <div class="text-3xl font-extrabold text-slate-800" id="ordersTotal">0</div>',
    '      </div>',
    '    </div>',
    '    <div class="bg-white border border-slate-200 rounded-xl">',
    '      <div class="px-5 py-4 border-b border-slate-100 flex justify-between items-center">',
    '        <span class="text-sm font-bold text-slate-800">Pedidos Recentes</span>',
    '        <button class="text-xs font-semibold text-slate-500 bg-slate-100 px-3 py-1.5 rounded-lg hover:bg-slate-200" onclick="showSection(\'orders\')">Ver todos</button>',
    '      </div>',
    '      <div id="recentOrdersBody" class="overflow-x-auto"><div class="text-center py-10 text-slate-400 text-sm">Carregando...</div></div>',
    '    </div>',
    '  </div>',
    '',
    '  <!-- ORDERS -->',
    '  <div id="sec-orders" class="section" style="display:none">',
    '    <div class="flex justify-between items-center mb-6">',
    '      <h1 class="text-2xl font-extrabold text-slate-900">Pedidos</h1>',
    '      <div class="flex gap-2">',
    '        <button class="text-xs font-semibold text-slate-500 bg-slate-100 px-3 py-1.5 rounded-lg hover:bg-slate-200" onclick="loadOrders()">Atualizar</button>',
    '        <button class="text-xs font-semibold text-red-600 bg-red-50 px-3 py-1.5 rounded-lg hover:bg-red-100" onclick="clearOrders()">Apagar todos</button>',
    '      </div>',
    '    </div>',
    '    <div class="bg-white border border-slate-200 rounded-xl">',
    '      <div id="ordersBody" class="overflow-x-auto"><div class="text-center py-10 text-slate-400 text-sm">Carregando...</div></div>',
    '    </div>',
    '  </div>',
    '',
    '  <!-- PIX CONFIG -->',
    '  <div id="sec-pix" class="section" style="display:none">',
    '    <div class="flex justify-between items-center mb-6">',
    '      <h1 class="text-2xl font-extrabold text-slate-900">Configuracao PIX</h1>',
    '      <div id="statusMsg" class="text-xs font-medium"></div>',
    '    </div>',
    '    <div class="bg-white border border-slate-200 rounded-xl">',
    '      <div class="px-5 py-4 border-b border-slate-100 flex justify-between items-center">',
    '        <span class="text-sm font-bold text-slate-800">PIX Copia e Cola</span>',
    '        <span class="text-xs text-slate-400 bg-slate-50 px-2 py-1 rounded">Atualizado: <span id="updated">-</span></span>',
    '      </div>',
    '      <div class="p-5">',
    '        <label class="block text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1.5">Codigo PIX</label>',
    '        <textarea id="pix" class="w-full border border-slate-200 rounded-lg p-3 text-xs font-mono bg-slate-50 focus:border-green-500 focus:ring-2 focus:ring-green-500/10 outline-none min-h-[100px] resize-y" placeholder="Cole aqui o codigo PIX..."></textarea>',
    '        <label class="block text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1.5 mt-4">QR Code (URL ou caminho)</label>',
    '        <input id="qr" class="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:border-green-500 focus:ring-2 focus:ring-green-500/10 outline-none" placeholder="assets/img/qrcode.webp"/>',
    '        <label class="flex items-center gap-2 text-sm text-slate-500 font-medium mt-3 cursor-pointer">',
    '          <input id="disableQr" type="checkbox" class="w-4 h-4 accent-green-600"/>',
    '          Desativar QR Code',
    '        </label>',
    '        <div class="flex gap-2 mt-5">',
    '          <button id="save" class="bg-green-600 hover:bg-green-700 text-white text-sm font-semibold px-5 py-2.5 rounded-lg transition-colors">Salvar</button>',
    '          <button id="reload" class="bg-slate-100 hover:bg-slate-200 text-slate-600 text-sm font-semibold px-5 py-2.5 rounded-lg transition-colors">Recarregar</button>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '',
    '  <!-- DIAGNOSTICS -->',
    '  <div id="sec-diagnostics" class="section" style="display:none">',
    '    <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3 mb-6">',
    '      <div>',
    '        <h1 class="text-2xl font-extrabold text-slate-900">Diagnostico mobile</h1>',
    '        <p class="text-sm text-slate-500 mt-1">Eventos tecnicos proprios, sem replay e sem valores de formulario.</p>',
    '      </div>',
    '      <div class="flex flex-wrap items-center gap-2">',
    '        <button class="text-xs font-semibold text-slate-500 bg-slate-100 px-3 py-1.5 rounded-lg hover:bg-slate-200" onclick="loadDiagnostics()">Atualizar</button>',
    '        <button class="text-xs font-semibold text-red-600 bg-red-50 px-3 py-1.5 rounded-lg hover:bg-red-100" onclick="clearDiagnosticsLogs()">Limpar logs</button>',
    '        <span id="diagnosticsStatus" class="text-xs text-slate-400"></span>',
    '      </div>',
    '    </div>',
    '    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">',
    '      <div class="bg-white border border-slate-200 rounded-xl p-5"><div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Eventos</div><div class="text-3xl font-extrabold text-slate-800" id="diagTotal">0</div></div>',
    '      <div class="bg-white border border-slate-200 rounded-xl p-5"><div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Sessoes</div><div class="text-3xl font-extrabold text-slate-800" id="diagSessions">0</div></div>',
    '      <div class="bg-white border border-slate-200 rounded-xl p-5"><div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">TikTok Ads</div><div class="text-3xl font-extrabold text-emerald-600" id="diagTikTokAds">0</div></div>',
    '      <div class="bg-white border border-slate-200 rounded-xl p-5"><div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">In-app TikTok</div><div class="text-3xl font-extrabold text-emerald-600" id="diagTikTokBrowser">0</div></div>',
    '    </div>',
    '    <div id="diagVerdictCard" class="bg-white border border-slate-200 rounded-xl p-5 mb-4">',
    '      <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3">',
    '        <div><div class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">Veredito automatico</div><div class="text-lg font-extrabold text-slate-800" id="diagVerdictTitle">Aguardando dados</div><div class="text-sm text-slate-500 mt-1" id="diagVerdictText">O analisador classifica sessoes por JS, API, assets, crawler e tracking externo.</div></div>',
    '        <div class="grid grid-cols-2 sm:grid-cols-4 gap-2 min-w-full lg:min-w-[420px]">',
    '          <div class="rounded-lg bg-emerald-50 px-3 py-2"><div class="text-[10px] font-semibold uppercase text-emerald-700">OK</div><div class="text-xl font-extrabold text-emerald-700" id="diagOk">0</div></div>',
    '          <div class="rounded-lg bg-amber-50 px-3 py-2"><div class="text-[10px] font-semibold uppercase text-amber-700">Alertas</div><div class="text-xl font-extrabold text-amber-700" id="diagWarnings">0</div></div>',
    '          <div class="rounded-lg bg-red-50 px-3 py-2"><div class="text-[10px] font-semibold uppercase text-red-700">Criticas</div><div class="text-xl font-extrabold text-red-700" id="diagCritical">0</div></div>',
    '          <div class="rounded-lg bg-purple-50 px-3 py-2"><div class="text-[10px] font-semibold uppercase text-purple-700">Crawler/HTML</div><div class="text-xl font-extrabold text-purple-700" id="diagNoise">0</div></div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '    <div id="diagFunnelCards" class="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-2 mb-6"></div>',
    '    <div class="grid grid-cols-1 xl:grid-cols-[360px_1fr] gap-4">',
    '      <div class="bg-white border border-slate-200 rounded-xl">',
    '        <div class="px-5 py-4 border-b border-slate-100 flex justify-between items-center"><span class="text-sm font-bold text-slate-800">Sessoes recentes</span><button class="text-xs font-semibold text-slate-500 bg-slate-100 px-2.5 py-1 rounded-lg hover:bg-slate-200" onclick="clearDiagSessionFilter()">Todas</button></div>',
    '        <div id="diagnosticsSessionList" class="p-3 text-sm text-slate-500 max-h-[560px] overflow-y-auto">Carregando...</div>',
    '      </div>',
    '      <div class="bg-white border border-slate-200 rounded-xl">',
    '        <div class="px-5 py-4 border-b border-slate-100 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-2"><div><span class="text-sm font-bold text-slate-800">Eventos da sessao</span><div class="text-xs text-slate-400 mt-0.5" id="diagSessionFilter">Todas as sessoes</div></div><div class="flex flex-wrap items-center gap-2"><button type="button" class="text-xs font-semibold text-slate-600 bg-slate-100 px-2.5 py-1.5 rounded-lg hover:bg-slate-200" onclick="copyDiagnosticsSummary()">Copiar resumo</button><button type="button" class="text-xs font-semibold text-slate-600 bg-slate-100 px-2.5 py-1.5 rounded-lg hover:bg-slate-200" onclick="copyDiagnosticsJson()">Copiar JSON</button><button type="button" class="text-xs font-semibold text-emerald-700 bg-emerald-50 px-2.5 py-1.5 rounded-lg hover:bg-emerald-100" onclick="downloadDiagnosticsJson()">Exportar JSON</button><button type="button" class="text-xs font-semibold text-emerald-700 bg-emerald-50 px-2.5 py-1.5 rounded-lg hover:bg-emerald-100" onclick="downloadAllDiagnosticSessionsJson()">Exportar todas</button><span class="text-xs text-slate-400" id="diagExportStatus"></span><span class="text-xs text-slate-400" id="diagUpdated">-</span></div></div>',
    '        <div id="diagnosticsBody" class="overflow-x-auto"><div class="text-center py-10 text-slate-400 text-sm">Carregando...</div></div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '',
    '</div>',
    '',
    '<script>',
    'var $=function(id){return document.getElementById(id)};',
    '',
    'function showSection(name){',
    '  document.querySelectorAll(".section").forEach(function(s){s.style.display="none"});',
    '  document.querySelectorAll(".nav-item").forEach(function(n){n.classList.remove("active")});',
    '  var sec=$("sec-"+name);',
    '  if(sec)sec.style.display="block";',
    '  var navs=document.querySelectorAll(".nav-item");',
    '  var idx={dashboard:0,orders:1,pix:2,diagnostics:3}[name];',
    '  if(navs[idx])navs[idx].classList.add("active");',
    '  if(name==="orders")loadOrders();',
    '  if(name==="diagnostics")loadDiagnostics();',
    '}',
    '',
    'function setStatus(h,ok){',
    '  $("statusMsg").innerHTML=ok!==false?"<span class=\\"text-green-600\\">"+h+"</span>":"<span class=\\"text-red-500\\">"+h+"</span>";',
    '}',
    '',
    'async function load(){',
    '  setStatus("Carregando...");',
    '  try{',
    '    var res=await fetch("/api/pix-config-admin?_="+Date.now(),{cache:"no-store"});',
    '    if(res.status===401){setStatus("401: credenciais invalidas.",false);return}',
    '    var data=await res.json();',
    '    if(!data||!data.ok)throw new Error("invalid");',
    '    $("pix").value=data.pix_code||"";',
    '    $("qr").value=(data.qrcode_url===null)?"":data.qrcode_url||"";',
    '    $("disableQr").checked=(data.qrcode_url===null);',
    '    $("updated").textContent=data.updated_at?new Date(data.updated_at).toLocaleString("pt-BR"):"-";',
    '    setStatus("Carregado.");',
    '  }catch(e){setStatus("Falha ao carregar.",false);console.error(e)}',
    '}',
    '',
    'async function save(){',
    '  var pix=$("pix").value.trim();',
    '  var disableQr=$("disableQr").checked;',
    '  var qr=$("qr").value.trim();',
    '  setStatus("Salvando...");',
    '  try{',
    '    var payload={pix_code:pix,qrcode_url:disableQr?null:(qr||"assets/img/qrcode.webp")};',
    '    var res=await fetch("/api/pix-config-admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});',
    '    if(res.status===401){setStatus("401: credenciais invalidas.",false);return}',
    '    var data=await res.json().catch(function(){return null});',
    '    if(!res.ok||!data||!data.ok){setStatus("Erro ao salvar.",false);return}',
    '    $("updated").textContent=data.updated_at?new Date(data.updated_at).toLocaleString("pt-BR"):"-";',
    '    setStatus("Salvo com sucesso!");',
    '  }catch(e){setStatus("Falha ao salvar.",false);console.error(e)}',
    '}',
    '',
    'async function loadMetrics(){',
    '  try{',
    '    var res=await fetch("/api/metrics/stats?_="+Date.now(),{cache:"no-store"});',
    '    if(res.status===401)return;',
    '    var data=await res.json().catch(function(){return null});',
    '    if(data&&data.ok){',
    '      $("pixClicks").textContent=data.pix_copy_clicks_total||"0";',
    '    }',
    '  }catch(e){}',
    '}',
    '',
    'var allOrders=[];',
    'var orderSyncInProgress={};',
    '',
    'async function loadOrders(){',
    '  try{',
    '    var res=await fetch("/api/orders?_="+Date.now(),{cache:"no-store"});',
    '    if(res.status===401)return;',
    '    var data=await res.json().catch(function(){return null});',
    '    if(data&&data.ok&&Array.isArray(data.orders)){',
    '      allOrders=data.orders;',
    '      renderOrders();',
    '      updateOrderStats();',
    '    }',
    '  }catch(e){}',
    '}',
    '',
    'function updateOrderStats(){',
    '  var today=new Date().toISOString().slice(0,10);',
    '  var todayCount=allOrders.filter(function(o){return o.created_at&&o.created_at.slice(0,10)===today}).length;',
    '  $("ordersToday").textContent=todayCount;',
    '  $("ordersTotal").textContent=allOrders.length;',
    '}',
    '',
    'function formatDate(iso){',
    '  if(!iso)return"-";',
    '  try{return new Date(iso).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}',
    '  catch(e){return iso}',
    '}',
    '',
    'function formatPhone(p){',
    '  if(!p)return"-";',
    '  var d=String(p).replace(/[^0-9]/g,"");',
    '  if(d.length===11)return"("+d.slice(0,2)+") "+d.slice(2,7)+"-"+d.slice(7);',
    '  if(d.length===13)return"+"+d.slice(0,2)+" ("+d.slice(2,4)+") "+d.slice(4,9)+"-"+d.slice(9);',
    '  return p;',
    '}',
    '',
    'function esc(s){if(!s)return"";return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}',
    'function truncateMiddle(s,max){var str=String(s||"");if(!str||str.length<=max)return str;var keep=Math.max(4,Math.floor((max-3)/2));return str.slice(0,keep)+"..."+str.slice(str.length-keep)}',
    'function renderOrderStatus(order){',
    '  var status=String((order&&order.status)||"pending").toLowerCase();',
    '  var syncStatus=String((order&&order.purchase_sync_status)||"").toLowerCase();',
    '  if(status==="paid"&&syncStatus==="sent")return"<div><span class=\\"inline-flex items-center rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700\\">Pago</span>"+(order.purchase_sent_at?"<div class=\\"text-[11px] text-slate-400 mt-1\\">Enviado: "+formatDate(order.purchase_sent_at)+"</div>":"")+"</div>";',
    '  if(status==="paid"&&syncStatus==="skipped")return"<div><span class=\\"inline-flex items-center rounded-full bg-sky-50 px-2.5 py-1 text-[11px] font-semibold text-sky-700\\">Pago</span>"+(order.paid_at?"<div class=\\"text-[11px] text-slate-400 mt-1\\">Pago: "+formatDate(order.paid_at)+"</div>":"")+"</div>";',
    '  if(status==="paid")return"<div><span class=\\"inline-flex items-center rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-semibold text-amber-700\\">Pago / sync pendente</span>"+(order.paid_at?"<div class=\\"text-[11px] text-slate-400 mt-1\\">Pago: "+formatDate(order.paid_at)+"</div>":"")+"</div>";',
    '  return"<div><span class=\\"inline-flex items-center rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-semibold text-amber-700\\">Pendente</span></div>";',
    '}',
    'function renderOrderActions(order){',
    '  if(!order||!order.id)return"-";',
    '  var isBusy=!!orderSyncInProgress[order.id];',
    '  var status=String(order.status||"pending").toLowerCase();',
    '  var syncStatus=String(order.purchase_sync_status||"").toLowerCase();',
    '  if(status==="paid"&&syncStatus==="sent")return"<span class=\\"text-xs text-slate-400\\">Sincronizado</span>";',
    '  var label=status==="paid"?"Reenviar Purchase":"Marcar como pago";',
    '  var className=status==="paid"?"bg-amber-50 text-amber-700 hover:bg-amber-100":"bg-emerald-50 text-emerald-700 hover:bg-emerald-100";',
    '  return"<button type=\\"button\\" onclick=\\"markOrderPaid(\\\'"+esc(order.id)+"\\\')\\" "+(isBusy?"disabled":"")+" class=\\"inline-flex items-center justify-center rounded-lg px-3 py-2 text-xs font-semibold transition-colors disabled:opacity-60 disabled:cursor-not-allowed "+className+"\\">"+(isBusy?"Enviando...":label)+"</button>";',
    '}',
    'function getOrderSourceObject(o){',
    '  if(o&&o.source&&typeof o.source==="object")return o.source;',
    '  var source={};',
    '  if(!o||typeof o!=="object")return source;',
    '  Object.keys(o).forEach(function(key){',
    '    if(key==="source")return;',
    '    if(key==="external_id"||key==="ttclid"||key==="gclid"||key==="fbclid"||key==="msclkid"||key.indexOf("utm_")===0||key.indexOf("tt_")===0)source[key]=o[key];',
    '  });',
    '  return source;',
    '}',
    'function pickSourceValue(source,keys){for(var i=0;i<keys.length;i++){var value=source[keys[i]];if(value)return value}return""}',
    'function renderOrderSource(source){',
    '  if(!source||!Object.keys(source).length)return"<div class=\\"text-xs text-slate-400\\">Sem origem salva</div>";',
    '  var primary=pickSourceValue(source,["tt_campaign","utm_campaign","tt_campaign_id","utm_source","external_id"])||"Origem identificada";',
    '  var adgroup=pickSourceValue(source,["tt_adgroup","tt_adgroup_id"]);',
    '  var creative=pickSourceValue(source,["tt_creative","tt_creative_id","tt_ad_id","utm_content"]);',
    '  var placement=pickSourceValue(source,["tt_placement"]);',
    '  var utmCombo=[source.utm_source,source.utm_medium].filter(Boolean).join(" / ");',
    '  var meta=[];',
    '  if(adgroup)meta.push("<div class=\\"text-xs text-slate-500\\">Conjunto: "+esc(truncateMiddle(adgroup,36))+"</div>");',
    '  if(creative)meta.push("<div class=\\"text-xs text-slate-500\\">Criativo: "+esc(truncateMiddle(creative,36))+"</div>");',
    '  var chips=[];',
    '  if(utmCombo)chips.push("<span class=\\"inline-flex items-center rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-600\\">"+esc(truncateMiddle(utmCombo,24))+"</span>");',
    '  if(placement)chips.push("<span class=\\"inline-flex items-center rounded-full bg-sky-50 px-2 py-0.5 text-[10px] font-medium text-sky-700\\">"+esc(truncateMiddle(placement,20))+"</span>");',
    '  if(source.ttclid)chips.push("<span class=\\"inline-flex items-center rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-medium text-emerald-700\\">TTCLID</span>");',
    '  if(!meta.length&&!chips.length){',
    '    Object.keys(source).slice(0,2).forEach(function(key){chips.push("<span class=\\"inline-flex items-center rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-600\\">"+esc(key)+": "+esc(truncateMiddle(source[key],16))+"</span>")});',
    '  }',
    '  return "<div class=\\"min-w-[220px]\\"><div class=\\"font-semibold text-slate-800\\">"+esc(truncateMiddle(primary,42))+"</div>"+meta.join("")+(chips.length?"<div class=\\"flex flex-wrap gap-1.5 mt-1.5\\">"+chips.join("")+"</div>":"")+"</div>";',
    '}',
    'function renderOrderDiagnostics(diagnostics){',
    '  var d=diagnostics&&typeof diagnostics==="object"?diagnostics:{};',
    '  if(!Object.keys(d).length)return"";',
    '  var session=d.session_id||"";',
    '  var env=[d.platform,d.browser_family].filter(Boolean).join(" / ");',
    '  var viewport=d.viewport_width&&d.viewport_height?(d.viewport_width+"x"+d.viewport_height):"";',
    '  var chips=[];',
    '  if(d.diagnostics_ready)chips.push("<span class=\\"inline-flex items-center rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-semibold text-emerald-700\\">Diag ativo</span>");',
    '  else chips.push("<span class=\\"inline-flex items-center rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-700\\">Diag parcial</span>");',
    '  if(d.is_tiktok_ad)chips.push("<span class=\\"inline-flex items-center rounded-full bg-green-50 px-2 py-0.5 text-[10px] font-semibold text-green-700\\">TikTok Ad</span>");',
    '  if(d.is_likely_tiktok_browser)chips.push("<span class=\\"inline-flex items-center rounded-full bg-green-50 px-2 py-0.5 text-[10px] font-semibold text-green-700\\">TikTok app</span>");',
    '  return "<div class=\\"mt-2 border-t border-slate-100 pt-2\\"><div class=\\"text-[11px] font-semibold text-slate-500\\">Diagnostico</div>"+(session?"<button type=\\"button\\" onclick=\\"openOrderDiagnostics(\\\'"+esc(session)+"\\\')\\" class=\\"text-[11px] font-semibold text-emerald-700 hover:text-emerald-800\\">Sessao "+esc(truncateMiddle(session,20))+"</button>":"<div class=\\"text-[11px] text-slate-400\\">Sem sessao</div>")+(env?"<div class=\\"text-[11px] text-slate-500\\">"+esc(env)+"</div>":"")+(viewport?"<div class=\\"text-[11px] text-slate-400\\">Tela "+esc(viewport)+"</div>":"")+(chips.length?"<div class=\\"flex flex-wrap gap-1 mt-1\\">"+chips.join("")+"</div>":"")+"</div>";',
    '}',
    'function renderOrderEdge(edge){',
    '  var e=edge&&typeof edge==="object"?edge:{};',
    '  if(!Object.keys(e).length)return"";',
    '  var bot=e.bot_management||{};',
    '  var parts=[];',
    '  if(e.country)parts.push(esc(e.country));',
    '  if(e.colo)parts.push("colo "+esc(e.colo));',
    '  if(e.asn)parts.push("ASN "+esc(e.asn));',
    '  if(e.as_organization)parts.push(esc(truncateMiddle(e.as_organization,28)));',
    '  if(e.tls_version)parts.push(esc(e.tls_version));',
    '  if(e.http_protocol)parts.push(esc(e.http_protocol));',
    '  var chips=[];',
    '  if(bot.score!==undefined)chips.push("<span class=\\"inline-flex items-center rounded-full bg-indigo-50 px-2 py-0.5 text-[10px] font-semibold text-indigo-700\\">Bot score "+esc(bot.score)+"</span>");',
    '  if(bot.verified_bot)chips.push("<span class=\\"inline-flex items-center rounded-full bg-sky-50 px-2 py-0.5 text-[10px] font-semibold text-sky-700\\">Bot verificado</span>");',
    '  if(bot.corporate_proxy)chips.push("<span class=\\"inline-flex items-center rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-700\\">Proxy corporativo</span>");',
    '  if(e.tls_fingerprint&&e.tls_fingerprint.client_extensions_sha1)chips.push("<span class=\\"inline-flex items-center rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-600\\">TLS FP</span>");',
    '  return "<div class=\\"mt-2 border-t border-slate-100 pt-2\\"><div class=\\"text-[11px] font-semibold text-slate-500\\">Cloudflare</div>"+(parts.length?"<div class=\\"text-[11px] text-slate-500\\">"+parts.join(" · ")+"</div>":"<div class=\\"text-[11px] text-slate-400\\">Sem metadados CF</div>")+(e.ray_id?"<div class=\\"text-[11px] text-slate-400\\">Ray "+esc(truncateMiddle(e.ray_id,22))+"</div>":"")+(chips.length?"<div class=\\"flex flex-wrap gap-1 mt-1\\">"+chips.join("")+"</div>":"")+"</div>";',
    '}',
    'function openOrderDiagnostics(sessionId){',
    '  if(!sessionId)return;',
    '  diagActiveSessionId=String(sessionId);',
    '  showSection("diagnostics");',
    '  loadDiagnostics();',
    '}',
    '',
    'function renderOrderTable(orders,containerId){',
    '  var el=$(containerId);',
    '  if(!orders.length){el.innerHTML="<div class=\\"text-center py-10 text-slate-400 text-sm\\">Nenhum pedido encontrado.</div>";return}',
    '  var h="<table class=\\"w-full text-sm\\"><thead><tr class=\\"bg-slate-50 border-b border-slate-200\\">";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Cliente</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Contato</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Origem</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Status</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase hidden lg:table-cell\\">Endereco</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Data</th>";',
    '  h+="<th class=\\"text-right px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Valor</th>";',
    '  h+="<th class=\\"text-right px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Ação</th>";',
    '  h+="</tr></thead><tbody>";',
    '  orders.forEach(function(o){',
    '    h+="<tr class=\\"border-b border-slate-50 hover:bg-slate-50\\">";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"font-semibold text-slate-800\\">"+esc(o.name)+"</div><div class=\\"text-xs text-slate-400 mt-0.5\\">"+esc(o.id)+"</div></td>";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"font-medium\\">"+esc(formatPhone(o.phone))+"</div><div class=\\"text-xs text-slate-400\\">"+esc(o.email)+"</div>"+(o.cpf?"<div class=\\"text-xs text-slate-400\\">CPF: "+esc(o.cpf)+"</div>":"")+"</td>";',
    '    h+="<td class=\\"px-4 py-3\\">"+renderOrderSource(getOrderSourceObject(o))+renderOrderDiagnostics(o.diagnostics)+renderOrderEdge(o.edge)+"</td>";',
    '    h+="<td class=\\"px-4 py-3\\">"+renderOrderStatus(o)+"</td>";',
    '    h+="<td class=\\"px-4 py-3 hidden lg:table-cell\\"><div class=\\"text-xs text-slate-500\\">"+esc(o.address||"-")+(o.number?", "+esc(o.number):"")+"</div><div class=\\"text-xs text-slate-400\\">"+esc(o.city||"-")+(o.cep?" - "+esc(o.cep):"")+"</div></td>";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"text-xs text-slate-500\\">"+formatDate(o.created_at)+"</div></td>";',
    '    h+="<td class=\\"px-4 py-3 text-right\\"><div class=\\"font-bold text-green-600\\">R$ "+(o.value||197.99).toFixed(2).replace(".",",")+"</div></td>";',
    '    h+="<td class=\\"px-4 py-3 text-right\\">"+renderOrderActions(o)+"</td>";',
    '    h+="</tr>";',
    '  });',
    '  h+="</tbody></table>";',
    '  el.innerHTML=h;',
    '}',
    '',
    'async function markOrderPaid(orderId){',
    '  if(!orderId||orderSyncInProgress[orderId])return;',
    '  var order=allOrders.find(function(item){return item&&item.id===orderId});',
    '  var status=(order&&order.status)||"pending";',
    '  var confirmText=status==="paid"?"Reenviar o evento Purchase desse pedido?":"Confirmar pagamento e enviar o evento Purchase para o TikTok?";',
    '  if(!confirm(confirmText))return;',
    '  orderSyncInProgress[orderId]=true;',
    '  renderOrders();',
    '  try{',
    '    var res=await fetch("/api/orders",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({id:orderId,status:"paid"})});',
    '    var data=await res.json().catch(function(){return null});',
    '    if(!res.ok||!data||!data.ok)throw new Error((data&&data.error)||"request_failed");',
    '    await loadOrders();',
    '    alert(data.already_synced?"Pedido já estava pago e sincronizado.":"Pedido marcado como pago e Purchase enviado.");',
    '  }catch(e){',
    '    console.error(e);',
    '    alert("Falha ao marcar como pago ou enviar o Purchase.");',
    '  }finally{',
    '    delete orderSyncInProgress[orderId];',
    '    renderOrders();',
    '  }',
    '}',
    '',
    'async function clearOrders(){',
    '  if(!confirm("Tem certeza que deseja apagar TODOS os pedidos? Esta acao nao pode ser desfeita."))return;',
    '  try{',
    '    var res=await fetch("/api/orders",{method:"DELETE"});',
    '    var data=await res.json().catch(function(){return null});',
    '    if(data&&data.ok){allOrders=[];renderOrders();updateOrderStats();alert("Pedidos apagados com sucesso.")}',
    '    else{alert("Erro ao apagar pedidos.")}',
    '  }catch(e){alert("Erro ao apagar pedidos.")}',
    '}',
    '',
    'function renderOrders(){',
    '  renderOrderTable(allOrders.slice(0,5),"recentOrdersBody");',
    '  renderOrderTable(allOrders,"ordersBody");',
    '}',
    '',
    'var diagEventNames={',
    '  client_boot_started:"Boot inline iniciado",',
    '  diagnostics_script_loaded:"Script diagnostico carregado",',
    '  critical_asset_loaded:"Asset critico carregado",',
    '  critical_asset_missing:"Asset critico falhou",',
    '  zaraz_loaded:"Zaraz carregado",',
    '  diagnostics_session_started:"Sessao iniciada",',
    '  page_loaded:"Pagina carregada",',
    '  checkout_opened:"Checkout aberto",',
    '  checkout_app_loaded:"App do checkout carregado",',
    '  checkout_ready:"Checkout pronto",',
    '  checkout_first_interaction:"Primeira interacao",',
    '  checkout_first_scroll:"Primeiro scroll",',
    '  checkout_first_field_focus:"Primeiro toque no campo",',
    '  checkout_keyboard_opened:"Teclado aberto",',
    '  checkout_field_visibility:"Campo visivel no foco",',
    '  checkout_pix_screen_loaded:"Tela PIX carregada",',
    '  checkout_pix_copy_attempt:"Tentativa de copiar PIX",',
    '  server_page_hit:"Entrada server-side",',
    '  server_asset_hit:"Asset pedido no servidor",',
    '  api_error:"Erro de API",',
    '  js_error:"Erro de JavaScript",',
    '  resource_error:"Erro de recurso",',
    '  slow_render:"Renderizacao lenta",',
    '  web_vital:"Web Vital",',
    '  ga_event_seen:"Evento GA visto"',
    '};',
    'var lastDiagnosticsData=null;',
    'var diagActiveSessionId="";',
    'var diagSessionsCurrent=[];',
    'function formatDiagEventName(name){return diagEventNames[name]||name||"-"}',
    'function eventTimeMs(iso){var t=Date.parse(iso||"");return isNaN(t)?0:t}',
    'function getDiagSessionId(ev){return ev&&ev.context&&ev.context.session_id?String(ev.context.session_id):"sem_sessao"}',
    'function getDiagEventKey(ev){var d=(ev&&ev.data)||{};return getDiagSessionId(ev)+"|"+String(ev&&ev.event)+"|"+String(ev&&ev.created_at)+"|"+String(d.resource_url||d.asset_url||"")}',
    'function getDiagSource(ctx){return [ctx&&ctx.platform,ctx&&ctx.browser_family].filter(Boolean).join(" / ")||"-"}',
    'function getDiagEventBotScore(ev){var bot=ev&&ev.edge&&ev.edge.bot_management?ev.edge.bot_management:null;return bot&&bot.score!==undefined&&bot.score!==null&&bot.score!==""?bot.score:""}',
    'function getDiagBotScoreClass(score){var n=Number(score);if(!Number.isFinite(n))return"bg-slate-100 text-slate-500";if(n<30)return"bg-red-50 text-red-700";if(n<60)return"bg-amber-50 text-amber-700";return"bg-indigo-50 text-indigo-700"}',
    'function getDiagAnalyzer(){return window.IzzatDiagnosticsAnalyzer&&typeof window.IzzatDiagnosticsAnalyzer.analyzeDiagnostics==="function"?window.IzzatDiagnosticsAnalyzer:null}',
    'function analyzeDiagEvents(events){var analyzer=getDiagAnalyzer();if(analyzer)return analyzer.analyzeDiagnostics(events||[]);var sessions=buildDiagSessions(events||[]);return{summary:summarizeDiagPanelEvents(events||[]),verdict:{label:"Analise basica",severity:"unknown",text:"Analisador profissional nao carregou; usando fallback simples."},sessions:sessions,events:events||[]}}',
    'function buildDiagSessions(events){',
    '  var analyzer=getDiagAnalyzer();if(analyzer&&typeof analyzer.buildSessions==="function")return analyzer.buildSessions(events||[]);',
    '  var map={};',
    '  events.forEach(function(ev){',
    '    var sid=getDiagSessionId(ev);var ctx=ev.context||{};var t=eventTimeMs(ev.created_at);',
    '    if(!map[sid])map[sid]={id:sid,events:[],count:0,first_at:ev.created_at,last_at:ev.created_at,first_ms:t,last_ms:t,ctx:ctx,bot_score:"",has_server:false,has_server_asset:false,has_server_js:false,has_server_css:false,has_client_boot:false,has_diag_script:false,has_css:false,has_checkout_script:false,has_zaraz:false,has_page_loaded:false,has_checkout:false,has_ready:false,has_field:false,has_pix:false,has_error:false,has_browser_event:false,is_crawler:false};',
    '    var s=map[sid];s.events.push(ev);s.count++;',
    '    var botScore=getDiagEventBotScore(ev);if(botScore!==""&&s.bot_score==="")s.bot_score=botScore;',
    '    if(t&&(!s.first_ms||t<s.first_ms)){s.first_ms=t;s.first_at=ev.created_at}',
    '    if(t&&(!s.last_ms||t>s.last_ms)){s.last_ms=t;s.last_at=ev.created_at;s.ctx=ctx}',
    '    var ua=(ctx.user_agent||"").toLowerCase();if(/bot|crawler|spider|externalhit|meta-externalagent|facebookexternalhit|preview/.test(ua))s.is_crawler=true;',
    '    if(ev.event==="server_page_hit")s.has_server=true;',
    '    if(ev.event==="server_asset_hit"){s.has_server_asset=true;if(ev.data&&ev.data.asset_type==="script")s.has_server_js=true;if(ev.data&&ev.data.asset_type==="style")s.has_server_css=true;}',
    '    if(ev.event==="client_boot_started")s.has_client_boot=true;',
    '    if(ev.event==="diagnostics_script_loaded"||ev.event==="diagnostics_session_started")s.has_diag_script=true;',
    '    if(ev.event==="page_loaded")s.has_page_loaded=true;',
    '    if(ev.event==="zaraz_loaded"||(ev.data&&/^zaraz_/.test(String(ev.data.asset_name||""))))s.has_zaraz=true;',
    '    if(ev.data&&ev.data.asset_name==="checkout_tailwind_css")s.has_css=true;',
    '    if(ev.data&&ev.data.asset_name==="checkout_app_js")s.has_checkout_script=true;',
    '    if(ev.event==="checkout_opened")s.has_checkout=true;',
    '    if(ev.event==="checkout_ready")s.has_ready=true;',
    '    if(ev.event==="checkout_first_field_focus")s.has_field=true;',
    '    if(ev.event==="checkout_pix_copy_attempt")s.has_pix=true;',
    '    if(ev.event==="api_error"||ev.event==="js_error"||ev.event==="resource_error"||ev.event==="critical_asset_missing")s.has_error=true;',
    '    if(ev.event&&ev.event!=="server_page_hit"&&ev.event!=="server_asset_hit")s.has_browser_event=true;',
    '  });',
    '  return Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return b.last_ms-a.last_ms});',
    '}',
    'function classifyDiagSession(s){',
    '  if(!s)return{label:"-",cls:"bg-slate-100 text-slate-600",hint:""};',
    '  if(s.analysis){var sev=s.analysis.severity;var cls=sev==="critical"?"bg-red-50 text-red-700":(sev==="warning"?"bg-amber-50 text-amber-700":(sev==="ok"?"bg-emerald-50 text-emerald-700":(sev==="noise"?"bg-purple-50 text-purple-700":"bg-slate-100 text-slate-600")));return{label:s.analysis.label,cls:cls,hint:s.analysis.hint||"",severity:sev,reasons:s.analysis.reasons||[]};}',
    '  if(s.is_crawler)return{label:"Crawler/preview",cls:"bg-purple-50 text-purple-700",hint:"User-agent de crawler ou preview social."};',
    '  if(s.has_error)return{label:"Erro provavel",cls:"bg-red-50 text-red-700",hint:"A sessao registrou erro JS, recurso ou API."};',
    '  if(s.has_pix||s.has_field||s.has_checkout)return{label:"Abertura real",cls:"bg-emerald-50 text-emerald-700",hint:"Houve interacao real no checkout."};',
    '  if(s.has_page_loaded||s.has_diag_script)return{label:"Abertura confirmada",cls:"bg-blue-50 text-blue-700",hint:"O navegador executou JS e confirmou carregamento."};',
    '  if(s.has_client_boot)return{label:"Interrompida cedo",cls:"bg-amber-50 text-amber-700",hint:"O inline rodou, mas o diagnostico completo nao confirmou carregamento."};',
    '  if(s.has_server_asset&&!s.has_browser_event)return{label:"Assets sem JS",cls:"bg-amber-50 text-amber-700",hint:"O navegador pediu assets criticos, mas nenhum JS confirmou execucao."};',
    '  if(s.has_server&&!s.has_browser_event)return{label:"HTML only",cls:"bg-orange-50 text-orange-700",hint:"Cloudflare recebeu a pagina, mas nenhum asset/JS confirmou vida."};',
    '  return{label:"Indefinida",cls:"bg-slate-100 text-slate-600",hint:"Sem sinais suficientes."};',
    '}',
    'function getDiagFunnelSummary(s){',
    '  var items=[];',
    '  items.push((s.has_server?"OK":"--")+" Server");',
    '  items.push((s.has_server_asset?"OK":"--")+" Asset req");',
    '  items.push((s.has_client_boot?"OK":"--")+" Boot");',
    '  items.push((s.has_diag_script?"OK":"--")+" Diag JS");',
    '  items.push((s.has_css?"OK":"--")+" CSS");',
    '  items.push((s.has_zaraz?"OK":"--")+" Zaraz");',
    '  items.push((s.has_page_loaded?"OK":"--")+" Load");',
    '  items.push((s.has_checkout?"OK":"--")+" Checkout");',
    '  return items;',
    '}',
    'function shouldShowDiagSession(s){',
    '  return !!(s&&s.has_browser_event);',
    '}',
    'function filterDiagEventsForPanel(events){',
    '  var raw=Array.isArray(events)?events:[];',
    '  var keep={};',
    '  buildDiagSessions(raw).forEach(function(s){if(shouldShowDiagSession(s))keep[s.id]=true});',
    '  return raw.filter(function(ev){return !!keep[getDiagSessionId(ev)]});',
    '}',
    'function summarizeDiagPanelEvents(events){',
    '  var sessions={};var tiktokAd=0;var tiktokBrowser=0;',
    '  (events||[]).forEach(function(ev){var ctx=ev.context||{};var sid=getDiagSessionId(ev);sessions[sid]=true;if(ctx.is_tiktok_ad)tiktokAd++;if(ctx.is_likely_tiktok_browser)tiktokBrowser++;});',
    '  return{total_events:(events||[]).length,unique_sessions:Object.keys(sessions).length,tiktok_ad_events:tiktokAd,likely_tiktok_browser_events:tiktokBrowser};',
    '}',
    'function renderDiagSessionList(events){',
    '  var sessions=buildDiagSessions(events).filter(shouldShowDiagSession);diagSessionsCurrent=sessions;',
    '  if(diagActiveSessionId&&!sessions.some(function(s){return s.id===diagActiveSessionId}))diagActiveSessionId="";',
    '  if(!sessions.length){$("diagnosticsSessionList").innerHTML="<div class=\\"text-center py-6 text-slate-400 text-sm\\">Nenhuma sessao com JS confirmada.</div>";return}',
    '  $("diagnosticsSessionList").innerHTML=sessions.map(function(s,i){',
    '    var ctx=s.ctx||{};var active=s.id===diagActiveSessionId;',
    '    var botScore=s.bot_score!==undefined&&s.bot_score!==null&&s.bot_score!==""?s.bot_score:"-";',
    '    var status=classifyDiagSession(s);',
    '    var chips=[status.label];if(ctx.is_tiktok_ad)chips.push("TikTok Ad");if(ctx.is_likely_tiktok_browser)chips.push("TikTok app");if(s.has_server)chips.push("Server");if(s.has_server_asset)chips.push("Asset req");if(s.has_server_js)chips.push("JS req");if(s.has_server_css)chips.push("CSS req");if(s.has_client_boot)chips.push("Boot");if(s.has_diag_script)chips.push("Diag JS");if(s.has_css)chips.push("CSS");if(s.has_zaraz)chips.push("Zaraz");if(s.has_page_loaded)chips.push("Load");if(!s.has_browser_event)chips.push("Sem JS");if(s.has_checkout)chips.push("Checkout");if(s.has_ready)chips.push("Pronto");if(s.has_field)chips.push("Campo");if(s.has_pix)chips.push("Copiou PIX");if(s.analysis&&s.analysis.critical_count)chips.push("Critico");else if(s.analysis&&s.analysis.warning_count)chips.push("Alerta");else if(!s.analysis&&s.has_error)chips.push("Erro");',
    '    chips.unshift("Bot score "+botScore);',
    '    var chipHtml=chips.map(function(c){var red=c==="Erro"||c==="Erro provavel"||c==="Critico";var warn=c==="Alerta"||c==="Sem JS"||c==="HTML only"||c==="Assets sem JS"||c==="Interrompida cedo";var info=c==="Abertura confirmada"||c==="Asset req"||c==="JS req"||c==="CSS req";var isCrawler=c==="Crawler/preview";var isBot=String(c).indexOf("Bot score ")===0;var cls=isBot?getDiagBotScoreClass(botScore):(red?"bg-red-50 text-red-700":(warn?"bg-amber-50 text-amber-700":(info?"bg-blue-50 text-blue-700":(isCrawler?"bg-purple-50 text-purple-700":"bg-emerald-50 text-emerald-700"))));return"<span class=\\"rounded-full "+cls+" px-2 py-0.5 text-[10px] font-semibold\\">"+esc(c)+"</span>"}).join("");',
    '    return"<button type=\\"button\\" onclick=\\"selectDiagSessionByIndex("+i+")\\" class=\\"w-full text-left rounded-xl border px-3 py-3 mb-2 transition-colors "+(active?"border-emerald-300 bg-emerald-50/70":"border-slate-100 bg-white hover:bg-slate-50")+"\\"><div class=\\"flex items-center justify-between gap-2\\"><span class=\\"font-semibold text-slate-800\\">Sessao "+esc(truncateMiddle(s.id,18))+"</span><span class=\\"text-xs font-bold text-slate-500 bg-slate-100 rounded-full px-2 py-0.5\\">"+s.count+"</span></div><div class=\\"text-xs text-slate-500 mt-1\\">"+esc(getDiagSource(ctx))+" · "+esc(ctx.viewport_width)+"x"+esc(ctx.viewport_height)+"</div><div class=\\"text-[11px] text-slate-400 mt-1\\">"+formatDate(s.first_at)+" ate "+formatDate(s.last_at)+"</div>"+(chipHtml?"<div class=\\"flex flex-wrap gap-1 mt-2\\">"+chipHtml+"</div>":"")+"</button>";',
    '  }).join("");',
    '}',
    'function selectDiagSessionByIndex(index){var s=diagSessionsCurrent[index];if(!s)return;diagActiveSessionId=s.id;if(lastDiagnosticsData)renderDiagnostics(lastDiagnosticsData)}',
    'function clearDiagSessionFilter(){diagActiveSessionId="";if(lastDiagnosticsData)renderDiagnostics(lastDiagnosticsData)}',
    'function renderDiagFunnelCards(events){',
    '  var el=$("diagFunnelCards");if(!el)return;',
    '  var sessions=buildDiagSessions(events||[]);',
    '  var counts={server:0,assetReq:0,jsReq:0,boot:0,diag:0,css:0,zaraz:0,load:0,checkout:0,htmlOnly:0,assetNoJs:0};',
    '  sessions.forEach(function(s){if(s.has_server)counts.server++;if(s.has_server_asset)counts.assetReq++;if(s.has_server_js)counts.jsReq++;if(s.has_client_boot)counts.boot++;if(s.has_diag_script)counts.diag++;if(s.has_css)counts.css++;if(s.has_zaraz)counts.zaraz++;if(s.has_page_loaded)counts.load++;if(s.has_checkout)counts.checkout++;if(s.has_server&&!s.has_server_asset&&!s.has_browser_event)counts.htmlOnly++;if(s.has_server_asset&&!s.has_browser_event)counts.assetNoJs++;});',
    '  var cards=[["Server",counts.server,"text-slate-800"],["Asset req",counts.assetReq,"text-blue-700"],["JS req",counts.jsReq,"text-blue-700"],["Boot inline",counts.boot,"text-blue-700"],["Diag JS",counts.diag,"text-blue-700"],["Load",counts.load,"text-emerald-700"],["Checkout",counts.checkout,"text-emerald-700"]];',
    '  el.innerHTML=cards.map(function(c){return"<div class=\\"bg-white border border-slate-200 rounded-lg px-3 py-2\\"><div class=\\"text-[10px] font-semibold text-slate-400 uppercase\\">"+esc(c[0])+"</div><div class=\\"text-xl font-extrabold "+c[2]+"\\">"+c[1]+"</div></div>"}).join("");',
    '}',
    'function getVisibleDiagnosticEvents(){',
    '  var events=filterDiagEventsForPanel(lastDiagnosticsData&&Array.isArray(lastDiagnosticsData.events)?lastDiagnosticsData.events:[]);',
    '  if(!diagActiveSessionId)return events.slice();',
    '  return events.filter(function(ev){return getDiagSessionId(ev)===diagActiveSessionId}).sort(function(a,b){return eventTimeMs(a.created_at)-eventTimeMs(b.created_at)});',
    '}',
    'function getDiagnosticExportPayload(){',
    '  var events=getVisibleDiagnosticEvents();',
    '  var first=events[0]||{};var last=events[events.length-1]||{};var ctx=first.context||{};',
    '  var analysis=analyzeDiagEvents(events);',
    '  return {exported_at:new Date().toISOString(),scope:diagActiveSessionId?"session":"loaded_events",session_id:diagActiveSessionId||null,event_count:events.length,first_event_at:first.created_at||"",last_event_at:last.created_at||"",summary:analysis.summary||{},verdict:analysis.verdict||{},source:{page_path:ctx.page_path||"",referrer:ctx.referrer||"",platform:ctx.platform||"",browser_family:ctx.browser_family||"",is_tiktok_ad:!!ctx.is_tiktok_ad,is_likely_tiktok_browser:!!ctx.is_likely_tiktok_browser,viewport_width:ctx.viewport_width||0,viewport_height:ctx.viewport_height||0,user_agent:ctx.user_agent||""},events:events};',
    '}',
    'function getDiagnosticSessionSource(events){',
    '  var first=(events&&events[0])||{};var ctx=first.context||{};',
    '  return {page_path:ctx.page_path||"",referrer:ctx.referrer||"",platform:ctx.platform||"",browser_family:ctx.browser_family||"",is_tiktok_ad:!!ctx.is_tiktok_ad,is_likely_tiktok_browser:!!ctx.is_likely_tiktok_browser,viewport_width:ctx.viewport_width||0,viewport_height:ctx.viewport_height||0,user_agent:ctx.user_agent||""};',
    '}',
    'function getAllDiagnosticSessionsExportPayload(){',
    '  var events=Array.isArray(lastDiagnosticsData&&lastDiagnosticsData.events)?lastDiagnosticsData.events:[];',
    '  var analysis=analyzeDiagEvents(events);',
    '  var sessions=(analysis.sessions||buildDiagSessions(events)).map(function(s){',
    '    var sessionEvents=(s.events||[]).slice().sort(function(a,b){return eventTimeMs(a.created_at)-eventTimeMs(b.created_at)});',
    '    var first=sessionEvents[0]||{};var last=sessionEvents[sessionEvents.length-1]||{};var status=classifyDiagSession(s);',
    '    return {session_id:s.id,event_count:sessionEvents.length,first_event_at:first.created_at||"",last_event_at:last.created_at||"",status:status.label,severity:(s.analysis&&s.analysis.severity)||"",reasons:(s.analysis&&s.analysis.reasons)||[],bot_score:s.bot_score||"",source:getDiagnosticSessionSource(sessionEvents),flags:{has_server:!!s.has_server,has_server_asset:!!s.has_server_asset,has_server_js:!!s.has_server_js,has_server_css:!!s.has_server_css,has_client_boot:!!s.has_client_boot,has_diag_script:!!s.has_diag_script,has_css:!!s.has_css,has_zaraz:!!s.has_zaraz,has_page_loaded:!!s.has_page_loaded,has_checkout:!!s.has_checkout,has_ready:!!s.has_ready,has_field:!!s.has_field,has_pix:!!s.has_pix,has_error:!!s.has_error,is_crawler:!!s.is_crawler},events:sessionEvents};',
    '  });',
    '  var orderedEvents=events.slice().sort(function(a,b){return eventTimeMs(a.created_at)-eventTimeMs(b.created_at)});var first=orderedEvents[0]||{};var last=orderedEvents[orderedEvents.length-1]||{};',
    '  return {exported_at:new Date().toISOString(),scope:"all_sessions",session_count:sessions.length,event_count:events.length,first_event_at:first.created_at||"",last_event_at:last.created_at||"",summary:analysis.summary||{},verdict:analysis.verdict||{},sessions:sessions};',
    '}',
    'function getDiagDataSummary(ev){',
    '  var d=(ev&&ev.data)||{};var edge=(ev&&ev.edge)||{};var bot=edge&&edge.bot_management?edge.bot_management:{};var parts=[];',
    '  ["event_name","event_id","interaction_type","field_name","field_type","api_name","error_name","error_message","error_filename","resource_type","resource_url","asset_name","asset_url","asset_type","asset_status","metric_name","checkout_visible_source","checkout_scroll_viewport"].forEach(function(k){if(d[k]!==undefined&&d[k]!==null&&d[k]!=="" )parts.push(k+": "+truncateMiddle(d[k],120))});',
    '  ["scroll_top","scroll_height","client_height","keyboard_delta","http_status","error_lineno","error_colno","lcp","cls","inp"].forEach(function(k){if(d[k]!==undefined&&d[k]!==null&&d[k]!=="" )parts.push(k+": "+d[k])});',
    '  ["ray_id","ip_country","colo","asn","as_organization","http_protocol","tls_version","client_tcp_rtt","client_quic_rtt"].forEach(function(k){if(edge[k]!==undefined&&edge[k]!==null&&edge[k]!=="" )parts.push("cf_"+k+": "+truncateMiddle(edge[k],80))});',
    '  if(bot.score!==undefined&&bot.score!==null&&bot.score!=="")parts.push("bot_score: "+bot.score);',
    '  return parts.join(" | ")||"-";',
    '}',
    'function buildDiagnosticsSummaryText(){',
    '  var payload=getDiagnosticExportPayload();var events=payload.events||[];',
    '  var lines=[];',
    '  lines.push("DIAGNOSTICO IZZAT - "+(payload.session_id?("SESSAO "+payload.session_id):"EVENTOS CARREGADOS"));',
    '  lines.push("Exportado em: "+payload.exported_at);',
    '  lines.push("Eventos: "+payload.event_count);',
    '  lines.push("Periodo: "+(payload.first_event_at||"-")+" ate "+(payload.last_event_at||"-"));',
    '  lines.push("Origem: "+(payload.source.platform||"-")+" / "+(payload.source.browser_family||"-")+" | TikTok Ad: "+(payload.source.is_tiktok_ad?"sim":"nao")+" | TikTok app: "+(payload.source.is_likely_tiktok_browser?"sim":"nao"));',
    '  lines.push("Viewport inicial: "+(payload.source.viewport_width||"-")+"x"+(payload.source.viewport_height||"-"));',
    '  lines.push("Pagina: "+(payload.source.page_path||"-"));',
    '  lines.push("User-Agent: "+(payload.source.user_agent||"-"));',
    '  lines.push("");',
    '  events.forEach(function(ev,i){var ctx=ev.context||{};lines.push((i+1)+". "+(ev.created_at||"-")+" | "+formatDiagEventName(ev.event)+" ("+ev.event+") | "+(ctx.page_path||"-")+" | "+(ctx.viewport_width||"-")+"x"+(ctx.viewport_height||"-")+" | "+getDiagDataSummary(ev));});',
    '  return lines.join("\\n");',
    '}',
    'function setDiagExportStatus(message,ok){',
    '  var el=$("diagExportStatus");if(!el)return;',
    '  el.textContent=message||"";',
    '  el.className="text-xs "+(ok===false?"text-red-500":"text-emerald-600");',
    '  if(message)setTimeout(function(){if(el.textContent===message)el.textContent=""},2200);',
    '}',
    'function copyTextToClipboard(text){',
    '  if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text);',
    '  return new Promise(function(resolve,reject){try{var ta=document.createElement("textarea");ta.value=text;ta.setAttribute("readonly","");ta.style.position="fixed";ta.style.left="-9999px";document.body.appendChild(ta);ta.select();var ok=document.execCommand("copy");document.body.removeChild(ta);ok?resolve():reject(new Error("copy_failed"))}catch(e){reject(e)}});',
    '}',
    'function copyDiagnosticsSummary(){',
    '  var text=buildDiagnosticsSummaryText();if(!text){setDiagExportStatus("Sem dados",false);return}',
    '  copyTextToClipboard(text).then(function(){setDiagExportStatus("Resumo copiado",true)}).catch(function(){setDiagExportStatus("Falha ao copiar",false)});',
    '}',
    'function copyDiagnosticsJson(){',
    '  var payload=getDiagnosticExportPayload();if(!payload.event_count){setDiagExportStatus("Sem dados",false);return}',
    '  copyTextToClipboard(JSON.stringify(payload,null,2)).then(function(){setDiagExportStatus("JSON copiado",true)}).catch(function(){setDiagExportStatus("Falha ao copiar",false)});',
    '}',
    'function downloadDiagnosticsJson(){',
    '  var payload=getDiagnosticExportPayload();if(!payload.event_count){setDiagExportStatus("Sem dados",false);return}',
    '  try{var name=(payload.session_id||"diagnostico_sessoes").replace(/[^a-z0-9_-]/gi,"_");var blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download=name+".json";document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(function(){URL.revokeObjectURL(url)},1000);setDiagExportStatus("JSON exportado",true)}catch(e){setDiagExportStatus("Falha ao exportar",false)}',
    '}',
    'function downloadAllDiagnosticSessionsJson(){',
    '  var payload=getAllDiagnosticSessionsExportPayload();if(!payload.session_count){setDiagExportStatus("Sem dados",false);return}',
    '  try{var blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="diagnostico_todas_sessoes.json";document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(function(){URL.revokeObjectURL(url)},1000);setDiagExportStatus("Todas exportadas",true)}catch(e){setDiagExportStatus("Falha ao exportar",false)}',
    '}',
    'function renderDiagVerdict(analysis){',
    '  var verdict=(analysis&&analysis.verdict)||{label:"Aguardando dados",severity:"unknown",text:"Sem eventos para analisar."};',
    '  var card=$("diagVerdictCard");var title=$("diagVerdictTitle");var text=$("diagVerdictText");if(!card||!title||!text)return;',
    '  var sev=verdict.severity||"unknown";',
    '  card.className="border rounded-xl p-5 mb-4 "+(sev==="critical"?"bg-red-50 border-red-200":(sev==="warning"?"bg-amber-50 border-amber-200":(sev==="ok"?"bg-emerald-50 border-emerald-200":"bg-white border-slate-200")));',
    '  title.className="text-lg font-extrabold "+(sev==="critical"?"text-red-800":(sev==="warning"?"text-amber-800":(sev==="ok"?"text-emerald-800":"text-slate-800")));',
    '  title.textContent=verdict.label||"Aguardando dados";',
    '  text.textContent=verdict.text||"Sem eventos para analisar.";',
    '}',
    'function renderDiagnostics(data){',
    '  lastDiagnosticsData=data||null;',
    '  var rawEvents=Array.isArray(data&&data.events)?data.events:[];',
    '  var events=filterDiagEventsForPanel(rawEvents);',
    '  var analysis=analyzeDiagEvents(events);',
    '  var summary=analysis.summary||summarizeDiagPanelEvents(events);',
    '  $("diagTotal").textContent=summary.total_events||0;',
    '  $("diagSessions").textContent=summary.unique_sessions||0;',
    '  $("diagTikTokAds").textContent=summary.tiktok_ad_sessions!==undefined?summary.tiktok_ad_sessions:(summary.tiktok_ad_events||0);',
    '  $("diagTikTokBrowser").textContent=summary.likely_tiktok_browser_sessions!==undefined?summary.likely_tiktok_browser_sessions:(summary.likely_tiktok_browser_events||0);',
    '  $("diagOk").textContent=summary.ok_sessions||0;',
    '  $("diagWarnings").textContent=summary.warning_sessions||0;',
    '  $("diagCritical").textContent=summary.critical_sessions||0;',
    '  $("diagNoise").textContent=(summary.crawler_sessions||0)+(summary.html_only_sessions||0);',
    '  renderDiagVerdict(analysis);',
    '  $("diagUpdated").textContent=data&&data.updated_at?new Date(data.updated_at).toLocaleString("pt-BR"):"-";',
    '  renderDiagFunnelCards(events);',
    '  renderDiagSessionList(events);',
    '  var visibleEvents=diagActiveSessionId?events.filter(function(ev){return getDiagSessionId(ev)===diagActiveSessionId}).sort(function(a,b){return eventTimeMs(a.created_at)-eventTimeMs(b.created_at)}):events;',
    '  var visibleAnalysis=analyzeDiagEvents(visibleEvents);var eventNotes={};(visibleAnalysis.sessions||[]).forEach(function(s){(s.event_analysis||[]).forEach(function(item){if(item&&item.event)eventNotes[getDiagEventKey(item.event)]=item})});',
    '  $("diagSessionFilter").textContent=diagActiveSessionId?("Sessao "+truncateMiddle(diagActiveSessionId,36)+" - "+visibleEvents.length+" eventos"):"Todas as sessoes - "+events.length+" eventos";',
    '  if(!visibleEvents.length){$("diagnosticsBody").innerHTML="<div class=\\"text-center py-10 text-slate-400 text-sm\\">Nenhum evento tecnico recebido.</div>";return}',
    '  var h="<table class=\\"w-full text-sm\\"><thead><tr class=\\"bg-slate-50 border-b border-slate-200\\">";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Evento</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Origem</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Tela</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Dados</th>";',
    '  h+="<th class=\\"text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase\\">Quando</th>";',
    '  h+="</tr></thead><tbody>";',
    '  visibleEvents.forEach(function(ev){',
    '    var ctx=ev.context||{};var d=ev.data||{};var edge=ev.edge||{};var bot=edge.bot_management||{};var note=eventNotes[getDiagEventKey(ev)]||{};',
    '    var source=getDiagSource(ctx);',
    '    var flags=[];if(ctx.is_tiktok_ad)flags.push("TikTok Ad");if(ctx.is_likely_tiktok_browser)flags.push("TikTok app");if(ctx.is_likely_in_app_browser&&!ctx.is_likely_tiktok_browser)flags.push("In-app");',
    '    var detail=[];["event_name","event_id","interaction_type","field_name","field_type","api_name","error_name","error_filename","resource_type","resource_url","asset_name","asset_url","asset_type","asset_status","initiator_type","ready_state","metric_name","checkout_visible_source","checkout_scroll_viewport"].forEach(function(k){if(d[k]!==undefined&&d[k]!==null&&d[k]!=="" )detail.push(k+": "+truncateMiddle(d[k],160))});',
    '    ["scroll_top","scroll_height","client_height","keyboard_delta","http_status","error_lineno","error_colno","lcp","cls","inp","start_time_ms","duration_ms","response_end_ms","transfer_size","encoded_body_size","decoded_body_size"].forEach(function(k){if(d[k]!==undefined&&d[k]!==null&&d[k]!=="" )detail.push(k+": "+d[k])});',
    '    ["ray_id","ip_country","colo","asn","as_organization","http_protocol","tls_version","client_tcp_rtt","client_quic_rtt"].forEach(function(k){if(edge[k]!==undefined&&edge[k]!==null&&edge[k]!=="" )detail.push("cf_"+k+": "+truncateMiddle(edge[k],120))});',
    '    if(bot.score!==undefined&&bot.score!==null&&bot.score!=="")detail.push("bot_score: "+bot.score);',
    '    if(d.error_message)detail.push("erro: "+truncateMiddle(d.error_message,70));',
    '    if(d.error_stack)detail.push("stack: "+truncateMiddle(d.error_stack,180));',
    '    if(ev.event==="js_error"&&String(d.error_message||"")==="Script error."&&!d.error_filename)detail.push("observacao: erro de script terceiro/cross-origin ocultado pelo navegador");',
    '    if(note.note)detail.unshift("analise: "+note.note);',
    '    var rowClass=note.severity==="critical"?"bg-red-50/60 hover:bg-red-50":(note.severity==="warning"?"bg-amber-50/50 hover:bg-amber-50":(note.severity==="noise"?"bg-purple-50/40 hover:bg-purple-50":"hover:bg-slate-50"));',
    '    h+="<tr class=\\"border-b border-slate-50 align-top "+rowClass+"\\">";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"font-semibold text-slate-800\\">"+esc(formatDiagEventName(ev.event))+"</div><div class=\\"text-xs text-slate-400 mt-0.5\\">"+esc(ev.event)+"</div>"+(!diagActiveSessionId?"<div class=\\"text-[11px] text-slate-400 mt-1\\">"+esc(truncateMiddle(getDiagSessionId(ev),20))+"</div>":"")+"</td>";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"font-medium text-slate-700\\">"+esc(source)+"</div>"+(flags.length?"<div class=\\"flex flex-wrap gap-1 mt-1\\">"+flags.map(function(f){return"<span class=\\"rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-semibold text-emerald-700\\">"+esc(f)+"</span>"}).join("")+"</div>":"")+"</td>";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"text-xs text-slate-600\\">"+esc(ctx.viewport_width)+"x"+esc(ctx.viewport_height)+"</div><div class=\\"text-xs text-slate-400\\">"+esc(truncateMiddle(ctx.page_path,42))+"</div></td>";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"text-xs text-slate-500 min-w-[260px]\\">"+(detail.length?esc(detail.join(" | ")):"-")+"</div></td>";',
    '    h+="<td class=\\"px-4 py-3\\"><div class=\\"text-xs text-slate-500 whitespace-nowrap\\">"+formatDate(ev.created_at)+"</div></td>";',
    '    h+="</tr>";',
    '  });',
    '  h+="</tbody></table>";',
    '  $("diagnosticsBody").innerHTML=h;',
    '}',
    'async function loadDiagnostics(){',
    '  try{',
    '    var res=await fetch("/api/diagnostics?_="+Date.now(),{cache:"no-store"});',
    '    if(res.status===401)return;',
    '    var data=await res.json().catch(function(){return null});',
    '    if(data&&data.ok)renderDiagnostics(data);',
    '    else $("diagnosticsBody").innerHTML="<div class=\\"text-center py-10 text-red-400 text-sm\\">Falha ao carregar diagnosticos.</div>";',
    '  }catch(e){$("diagnosticsBody").innerHTML="<div class=\\"text-center py-10 text-red-400 text-sm\\">Falha ao carregar diagnosticos.</div>"}',
    '}',
    'async function clearDiagnosticsLogs(){',
    '  if(!confirm("Apagar todos os logs de diagnostico? Esta acao nao pode ser desfeita."))return;',
    '  var status=$("diagnosticsStatus");',
    '  if(status){status.textContent="Limpando...";status.className="text-xs text-slate-400"}',
    '  try{',
    '    var res=await fetch("/api/diagnostics",{method:"DELETE"});',
    '    if(res.status===401){if(status){status.textContent="401: acesso negado";status.className="text-xs text-red-500"}return}',
    '    var data=await res.json().catch(function(){return null});',
    '    if(!res.ok||!data||!data.ok)throw new Error("delete_failed");',
    '    diagActiveSessionId="";',
    '    diagSessionsCurrent=[];',
    '    renderDiagnostics({ok:true,updated_at:data.updated_at||new Date().toISOString(),summary:{total_events:0,unique_sessions:0,tiktok_ad_events:0,likely_tiktok_browser_events:0},events:[]});',
    '    $("diagnosticsBody").innerHTML="<div class=\\"text-center py-10 text-slate-400 text-sm\\">Logs apagados.</div>";',
    '    setDiagExportStatus("");',
    '    if(status){status.textContent="Logs apagados: "+(data.deleted||0);status.className="text-xs text-emerald-600";setTimeout(function(){if(status.textContent.indexOf("Logs apagados")===0)status.textContent=""},2500)}',
    '  }catch(e){',
    '    if(status){status.textContent="Falha ao limpar";status.className="text-xs text-red-500"}',
    '    alert("Falha ao limpar logs de diagnostico.");',
    '  }',
    '}',
    '',
    'function init(){',
    '  $("reload").addEventListener("click",load);',
    '  $("save").addEventListener("click",save);',
    '  $("disableQr").addEventListener("change",function(){',
    '    $("qr").disabled=$("disableQr").checked;',
    '    if($("disableQr").checked)$("qr").value="";',
    '  });',
    '  load();loadMetrics();loadOrders();',
    '  setInterval(loadMetrics,30000);',
    '  setInterval(loadOrders,30000);',
    '  setInterval(function(){var sec=$("sec-diagnostics");if(sec&&sec.style.display!=="none")loadDiagnostics()},30000);',
    '}',
    'init();',
    '<\/script>',
    '</body>',
    '</html>',
  ].join('\n');

  return page;
}

function htmlResponse(body, status = 200) {
  return new Response(body, {
    status,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store, max-age=0',
    },
  });
}

export async function onRequestGet(context) {
  if (!checkBasicAuth(context.request, context.env)) return unauthorized();
  return htmlResponse(serveHTML());
}
